### ISSUE TITLE
Can you help me with this problem?

### ISSUE THREAD

**Issue by mozixun-me** [MickiusMousius/RolioKeyboard#10]
![WechatIMG620](https://github.com/MickiusMousius/RolioKeyboard/assets/106295352/b968cc3c-6df8-4700-a843-e968681b4f92)
What method do you use to extend the Type-C interface in the part circled in the picture?

**Comment by MickiusMousius** [comment]
It’s just a 3D printed shroud, I’ve attached a CAD picture that shows it (hopefully).

![IMG_0123](https://github.com/MickiusMousius/RolioKeyboard/assets/137600636/b04d3195-b8fe-49b8-a7ac-6f91b2674485)
